### ISSUE TITLE
SEO for Titles

### ISSUE THREAD

**Issue by codetricity** [codetricity/oppkey-summer-of-code-2022#7]
For the tutorial titles, consider SEO best-practices similar to what we are getting recommended on Yoast.  Consider putting the key phrase that the developer would search for in the title.

1. Sending RICOH THETA API Requests with HTTP and WiFi
2. Managing RICOH THETA API JSON Responses for Mobile Apps
3. Displaying Thumbnails Using the RICOH THETA API and Mobile App State Management

Reference

[https://yoast.com/wordpress-seo/](Yoast SEO guidelines for Wordpress)

**Comment by codetricity** [comment]
As there was no response, I started to improve the SEO using the term RICOH THETA API.

af9b3b378bfd794af38d4e4ed9fe750026619496

**Comment by jcasman** [comment]
OK

**Comment by codetricity** [comment]
feel free to continue with the SEO process

**Comment by codetricity** [comment]
Added Google G-Tag plug-in for analytics.  I'm not sure if it is working properly.
Added description to site metadata.  It kind of looks like the tag is there.

```
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-DSEPQZKM1K"></script>
<script>
  if(true) {
   window.dataLayer = window.dataLayer \|\| [];
   function gtag(){window.dataLayer && window.dataLayer.push(arguments);}
   gtag('js', new Date());
    
   gtag('config', 'G-DSEPQZKM1K', {"send_page_view":false});
   }
   </script>
```
